cloudflare:
    caddy_env: ENC[AES256_GCM,data:MaLxUa/oooLT9VlTQl81q6Q5yOxWuiXbo9Lcrww4sfk2CmbP/Oj0pxqtb7I9c7ge2UNtidnatAFUqLfHXlW3Zt9iENceQVxW3/86,iv:I+qNH4obhnXMpVxhcJgakzsWNj1lMyoN/6UCQ12id2M=,tag:BTD5nvHp1Aj7D7MtxmaoMA==,type:str]
    cloudflared_tunnel_credentials: ENC[AES256_GCM,data:Xs8WKVhIudO0fLf30bAomQhX0S6LtHlILYyetp0NO/6d9ZgBYlROaVcm5xrbpv9vcAoUFBCXI0WDDAkjuGWzcF+vcPeRZZRsJXPZoZlS9kX8pIQ1fSHgC/0gi4DmriK5KzFvVpor7J+1Qb2KbHjuZhhfwmoZkc1C6i5CMnLwSzouiUO6GAJgnF2NZYwTlWPyQBc+4Ot6bJL4KFDC+0Cfh88Q93fcPvpdxaIt9j7aLA==,iv:k8oElv7F6QSYW54hoU1asvERBcoXdqlSIeHuwG1lJxI=,tag:C+9VfQ5F4c2NYLsaijeTNg==,type:str]
grafana:
    admin_password: ENC[AES256_GCM,data:QAJdBFBvdVA=,iv:b7wP7NfpNx91acroZ7HrPwGcVvpqFRmo94VKEf6GOK4=,tag:bI4+vtyKgr486j9vWRh3KQ==,type:str]
    secret_key: ENC[AES256_GCM,data:rTOKut5kGJ0OwDRfxvWA8FiqBFw=,iv:J30sd3mVxO/AD6m2XfFjJhXtmKgAazJRwEgJzzgDaho=,tag:6pjhK5a35xqFeVWH/82m5w==,type:str]
    renderer_token: ENC[AES256_GCM,data:pch3Ql+2SIRhAqdoe978fh/rfOJ/Oo8+xKhyPcmuxItketyYlRROgzP2kwCem0sVSbWS5OdENxYQ0UKpoAYGAQ==,iv:Dh2cdIC66EeamZsgPx/AtFMQhO0Ol4SN9JsnQO1BLYU=,tag:6uIAvuRMqbrxbNUZE3G92Q==,type:str]
    renderer_env: ENC[AES256_GCM,data:0N2Dl5H+CdLugqxddrcgjrlRaW/+0DchvFyfbA9vCA3VJ9PevKo3WQNJ6w2BwZ6F+bhmDIrQdvHN1rifqOC3gnho2U6ylMar9WT4,iv:fykspVRpWbcyFbiAvZuND4mufZpfB+tgYqesIKJBlTA=,tag:0dn98FyjAhWS6Hx2dqd0LQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Vy9wMVZwNldSazA1S3cz
            TVJuQkhOaDBHN1hJV3NaMHNrSGMzL3VSNmhFCkJVZmxvdzdrTHoxbjBYbHBqa3h6
            anQ2enRuU2tpQnBpUUx6L0ErTWhkMUUKLS0tIG4zLzFqMzJ6bG82by9YNzRtQnI4
            RXhQYUFMYU9RR1RoRUVnNWlpdGJ5MlEKxlbHUBR/MoDV/nyWeX32m112/BXr32wH
            l+50eSrbbpLjD6WSG0i3D7Dxoq5yzkHxGeO40/zZyMsc4OjdqboeqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qeyrh6e40nek3da4mnj298cy2l3aswe7432us30d2p93akcvp9zqext63j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bFVUclVDM0lUanYwU3lh
            QWZWZmVkQTBnWWx0Z3NaK3NOYTBRaFdtbFdZCmJGdE83Zk50ckRPY2tWT3l4TXoy
            ZGJPMkI3dzMxRzRkaG1acTBNWUZWQ2MKLS0tIE16WmxmS1EydTJ1bm1CNmwzeG5q
            ZFhtVjVqaUJoRUJ5OXBCQThVUU5HbDAK9P1OnxXycp7Fv4XKIunZpNHR4Os0ocKI
            N826u7XI8mEtO2ml6uIe9SITl09c36g32w21oIFHvk6X/rLLmAHA2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10zgc2lj0j8zfetrysupdumftrq2esmud2xru2hn5228rk6v45p2sa2t4k0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcGoxekJNTUJJQXlxUjlz
            NGU2dWZwcHNLbWNXOE5IU3lsNXNMN3dpa2cwCnR2bm9BVFRPRjN6TjQxZVh1NEV2
            TW9NNEkzemZRM3NyajlFQ2ZFamptNzAKLS0tIGFzZVgyNVJmNmxudEd2d0JiU0hk
            QVUyKzRLMzJWVEJvVDdpYVRSblRVNU0K9W/w/HlX3OlmZsLDkyfhmsZ7nBhVAczj
            TdZcEc0hUy/9cIv0v8p6acz2XNgBUYXCF3ORJMOsvH/pLbyoEj3rng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g2fpds2u6rz02pejpr05uu7r596fz5gvwz4jg7sahjktp67n39psukvng9
    lastmodified: "2026-06-04T10:04:08Z"
    mac: ENC[AES256_GCM,data:M7SL6lVImIYNVIGt+0Ez2QiIlkurvN7LCucbDilV2UZLKkbbbyugh2ji4cqkbLweb0MBMjVqS3hvsBeUTV5q4I4ztDjeaBK1Q9Ykx9mkt8v9KS4Ii47QbPax29P1uVZjpy8D+w52kpEqa1VvKtTyG7xDV7MYSAYSnDO/1TMxEOE=,iv:Sopz1bGRcjGN2wOUm02XY/va0j4rheDXtwlbYtrpIlg=,tag:cRx7hBieY9EBXJ6vf2B+Ig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
